import{S as f,i as m}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const l="46333898-2c3ef88233fdb340cf3d447ca",d=n=>{const r=new URLSearchParams(n);return fetch(`https://pixabay.com/api/?key=${l}&${r}`).then(s=>{if(!s.ok)throw new Error("opps");return s.json()})},a=document.querySelector(".gallery"),g=new f(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.7}),h=n=>{const r=n.map(({webformatURL:s,largeImageURL:o,tags:e,likes:t,views:i,comments:p,downloads:u})=>`<li class="gallery-item">
      <a href="${o}" class="gallery-link"><img src="${s}" alt="${e}" class="gallery-img"></a>
      <div class="info-wrapper">
        <p class="info-item">likes<span>${t}</span></p>
        <p class="info-item">views<span>${i}</span></p>
        <p class="info-item">comments<span>${p}</span></p>
        <p class="info-item">downloads<span>${u}</span></p>
      </div>
    </li>`).join("");a.innerHTML=r,g.refresh(),a.addEventListener("click",s=>s.preventDefault())},y=document.querySelector(".js-search-form"),c=document.querySelector(".loader-js");y.addEventListener("submit",L);function L(n){n.preventDefault(),a.innerHTML="";const r=n.currentTarget;if(r.elements.query.value==="")return;c.classList.toggle("loader");const s={key:l,q:r.elements.query.value,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:50};d(s).then(o=>{console.log(o.hits),o.hits.length===0&&m.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c.classList.toggle("loader"),h(o.hits)}).catch(o=>console.error(o))}
//# sourceMappingURL=index.js.map
